### ISSUE TITLE
forkFFT subtraction wrong order

### ISSUE THREAD

**Issue by Bushuo** [HED-GIT/TU_WIEN_BETRIEBSSYSTEME#1]
Hi,
the subtraction in forkFFT on line 240 is in the wrong order
```c
subtract(new2, &o);
```

this would result in new2 = new2 - o
but the formula requires it to be new2 = o - new2

EDIT: messed up the initial post

**Comment by HED-GIT** [comment]
thanks, should be merged now

weird that the one i actually submitted has such an error, i should probably refactor all of forkfft and some others since they have some ... questionable codepieces.
