### ISSUE TITLE
genpdfs.sh script doesn't work

### ISSUE THREAD

**Issue by maerqin** [HED-GIT/TU_WIEN_BETRIEBSSYSTEME#3]
The script genpdfs.sh iterates through all the files and generates a pdf document with pdflatex when the file ends with ".tex". The issue is that there is one file named BonusExercise.tex from which a pdf document can not be created, because it doesn't have the necessary wrapping for a latex document and is used as a section in other documents. That is why the script crashes when it is run. I fixed the issue by skipping the iteration when the file is found. The code that I implemented at the start of the iteration is posted below.

```
if [ $file ==  "./regular/2/BonusExercise.tex" ]; 
then
 continue
fi
```

**Comment by HED-GIT** [comment]
i assume you wanted to post that on the exercises repository of the osue team, right?
